spring:
  profiles.active: default
---
spring:
  profiles: default

serial:
  port: COM4

local:
  server:
    port: 8080

metrics:
  frequency: 10
  console: false
  jmx: false
  slf4j: true

pin:
  red: 10
  green: 11
  blue: 13

