spring:
  profiles.active: default
---
spring:
  profiles: default

serial:
  port: COM3

local:
  server:
    port: 8080

metrics:
  frequency: 10
  console: false
  jmx: false
  slf4j: true

pin:
  red: 3
  green: 5
  blue: 6

